//This defines the tweet class that defines tweets generated by the TwitterBot
//Tweet has fields that denote what the tweet is

public class Tweet{


	private final String Sentiment;
	private final String TweetID;
	private final String TweetTopic;
	private final String TweetText;

//Here are the getter methods for obtaining the sentiment/ID/Topic/Text. Each field is returned form the parsed list created
//in twitterbot referred to as "MyTweets".

	public String getSentiment() { return(this.Sentiment);
	}

	public String getTweetID() { return(this.TweetID); }

	public String getTweetTopic() { return(this.TweetTopic);
	}

	public String getTweetText() {
		return(this.TweetText);
	}

//This is the tweet object itself, with setter methods for Sentiment,TweetID,Topic,and Text. These fields are pulled
//from the afformentioned "Mytweets" array.

	public Tweet(String Sentiment, String TweetID, String TweetTopic, String TweetText) {
		this.Sentiment = Sentiment;
		this.TweetID = TweetID;
		this.TweetTopic = TweetTopic;
		this.TweetText = TweetText;
	}
  }



